version: '3.8'

services:
  db:
    image: postgres:14
    container_name: aracar_db
    environment:
      POSTGRES_USER: victor
      POSTGRES_PASSWORD: victor
      POSTGRES_DB: aracar_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aracar-network
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: aracar_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - aracar-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://aracar_db:5432/aracar_db
      SPRING_DATASOURCE_USERNAME: victor
      SPRING_DATASOURCE_PASSWORD: victor
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

networks:
  aracar-network:
    driver: bridge

volumes:
  postgres_data:
