version: '3.8'

services:
  db:
    image: postgres:14
    container_name: aracar_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aracar-network
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: aracar_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - aracar-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

networks:
  aracar-network:
    driver: bridge

volumes:
  postgres_data:
